Add eng and placeholders for reset metadata notice
sboesen/langs pull request #32
Opened 2024-03-07 06:57 UTC by kadisonm

2024-03-07 07:10 UTC, bytemain commented
I can help fill these chinese placeholder out, can I just make comments?

2024-03-07 07:10 UTC, bytemain commented on zh_cn.json
> +  "settings_reset_sync_metadata_notice_start": "Deleting, please wait... (1/2)",
删除中，请等待... (1/2)

2024-03-07 07:11 UTC, bytemain commented on zh_cn.json
> +  "settings_reset_sync_metadata_notice_error": "Already deleting, please wait.",
已开始删除远程元数据文件，请耐心等待。

2024-03-07 07:11 UTC, kadisonm commented
Thanks, I appreciate that! By the way, I just added another one for if they try to reset while it is already resetting.

2024-03-07 07:12 UTC, bytemain commented on zh_tw.json
> +  "settings_reset_sync_metadata_notice_start": "Deleting, please wait... (1/2)",
刪除中，請等待... (1/2)

2024-03-07 07:13 UTC, bytemain commented on zh_tw.json
> +  "settings_reset_sync_metadata_notice_error": "Already deleting, please wait.",
已開始刪除遠程元數據文件，請耐心等待。

2024-03-07 07:14 UTC, bytemain commented on zh_tw.json
> +  "settings_reset_sync_metadata_notice_error": "Already deleting, please wait.",
已開始刪除遠端中繼資料檔案，請耐心等待。

2024-03-07 07:17 UTC, kadisonm commented
I pushed them to the branch. Thanks a lot!

2024-03-07 07:18 UTC, bytemain requested changes

2024-03-07 07:18 UTC, bytemain commented on zh_tw.json
> +  "settings_reset_sync_metadata_notice_error": "已開始刪除遠程元數據文件，請耐心等待。",
已開始刪除遠端中繼資料檔案，請耐心等待。

@kadisonm oh, I made a update for this sentence, cause the words we use everyday are not the same

2024-03-10 02:52 UTC, merged

2024-03-10 02:52 UTC, sboesen commented
Thank you both for the update & translations!! Merged.